Imports System
Imports System.IO
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe09-03.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe09_03

    Private Sub cmdProcessAll_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdProcessAll.Click

        ProcessControls(Me)

    End Sub
    Private Sub ProcessControls(ByVal ctrl As Control)

        '  Ignore the control unless it's a textbox.
        If TypeOf (ctrl) Is TextBox Then
            ctrl.Text = ""
        End If

        '  Process controls recursively.  This is required
        '  if controls contain other controls (for
        '  example, if you use panels, group boxes, or other
        '  container controls).
        For Each ctrlChild As Control In ctrl.Controls
            ProcessControls(ctrlChild)
        Next

    End Sub

End Class
