Imports System
Imports System.Windows.Forms
Imports System.Xml.Xsl
'  All designed code is stored in the autogenerated partial
'  class called TransformXML.Designer.vb. You can see this
'  file by selecting Show All Files in Solution Explorer.
Partial Public Class TransformXml

    Private Sub TransformXml_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Dim transform As New XslCompiledTransform

        '  Load the XSLT stylesheet.
        transform.Load("Xml2Html.xslt")

        '  Transform EmployeeRoster.xml into Employees.html using
        '  the previously generated stylesheet.
        transform.Transform("EmployeeRoster.xml", "EmployeeRoster.html")

        Browser.Navigate(Application.StartupPath & "\EmployeeRoster.html")

    End Sub

End Class
