Imports System
Imports System.Threading
Imports System.Globalization
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe09-12.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe09_12

    Public Shared Sub Main()

        Thread.CurrentThread.CurrentUICulture = New CultureInfo("fr-FR")
        Application.Run(New Recipe09_12)

    End Sub

End Class