Imports System
Imports System.Drawing
Imports System.Windows.Forms
Imports System.Drawing.Printing
'  All designed code is stored in the autogenerated partial
'  class called Recipe10-16.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe10_16

    Private Sub cmdPrint_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdPrint.Click

        '  Create the document and attach an event handler.
        Dim text As String = "Windows Server 2003 builds on the core strengths " & _
        "of the Windows family of operating systems--security, manageability, " & _
        "reliability, availability, and scalability. Windows Server 2003 " & _
        "provides an application environment to build, deploy, manage, and " & _
        "run XML web services. Additionally, advances in Windows Server 2003 " & _
        "provide many benefits for developing applications."

        Dim doc As New ParagraphDocument(text)
        AddHandler doc.PrintPage, AddressOf Doc_PrintPage

        '  Allow the user to choose a printer and specify other settings.
        Dim dlgsettings As New PrintDialog
        dlgsettings.Document = doc

        '  If the user clicked OK, print the document.
        If dlgsettings.ShowDialog = Windows.Forms.DialogResult.OK Then
            doc.Print()
        End If

    End Sub
    Private Sub Doc_PrintPage(ByVal sender As Object, ByVal e As PrintPageEventArgs)

        '  Retrieve the document that sent this event.
        Dim doc As ParagraphDocument = DirectCast(sender, ParagraphDocument)

        '  Define the font and text.
        Using fnt As New Font("Arial", 35)
            e.Graphics.DrawString(doc.Text, Font, Brushes.Black, e.MarginBounds, StringFormat.GenericDefault)
        End Using

    End Sub
End Class
Public Class ParagraphDocument
    Inherits PrintDocument

    Private m_Text As String
    Public Sub New(ByVal txt As String)
        Me.Text = txt
    End Sub
    Public Property Text() As String
        Get
            Return m_Text
        End Get
        Set(ByVal value As String)
            m_Text = value
        End Set
    End Property

End Class