Imports System
Imports System.Windows.Forms
Imports QuartzTypeLib
'  All designed code is stored in the autogenerated partial
'  class called Recipe10-11.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe10_11

    Dim graphManager As QuartzTypeLib.FilgraphManager
    Private Sub cmdOpen_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdOpen.Click

        '  Allow the user to choose a file.
        Dim openDialog As New OpenFileDialog

        openDialog.Filter = "Media FIles|*.wav;*.mp3;*.mp2;*.wma|All Files|*.*"

        If openDialog.ShowDialog = Windows.Forms.DialogResult.OK Then
            '  Access the IMediaControl interface.
            graphManager = New QuartzTypeLib.FilgraphManager
            Dim mc As QuartzTypeLib.IMediaControl = DirectCast(graphManager, QuartzTypeLib.IMediaControl)

            '  Specify the file.
            mc.RenderFile(openDialog.FileName)

            Try
                mc.Run()
            Catch ex As Exception
                MessageBox.Show("An error occurred while playing media.")
            End Try

        End If

    End Sub
    Private Sub Recipe10_11_FormClosing(ByVal sender As Object, ByVal e As System.Windows.Forms.FormClosingEventArgs) Handles Me.FormClosing

        If graphManager IsNot Nothing Then
            '  Destroy the COM object (QuartzTypeLib) that we are using.
            System.Runtime.InteropServices.Marshal.ReleaseComObject(graphManager)
        End If

    End Sub

End Class