Imports System
Imports System.Drawing
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe10-05.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Public Class Recipe10_05

    Private Sub Recipe10_05_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Dim text As String = "The quick brown fox jumps over the lazy dog."

        Using fnt As New Font("Tahoma", 14)
            '  Create an in-memory bitmap.
            Dim bmp As New Bitmap(600, 600)

            Using g As Graphics = Graphics.FromImage(bmp)
                g.FillRectangle(Brushes.White, New Rectangle(0, 0, bmp.Width, bmp.Height))

                '  Draw several lines of text on the bitmap.
                For i As Integer = 1 To 10
                    g.DrawString(text, fnt, Brushes.Black, 50, 50 + i * 60)
                Next

            End Using

            '  Display the bitmap in the picture box.
            pictureBox1.BackgroundImage = bmp
            pictureBox1.Size = bmp.Size

        End Using

    End Sub

End Class
