Imports System
Imports System.Drawing
Imports System.Drawing.Drawing2D
'  All designed code is stored in the autogenerated partial
'  class called EllipseShape.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Public Class EllipseShape
    Inherits System.Windows.Forms.Control

    Dim path As GraphicsPath = Nothing
    Private Sub RefreshPath()

        '  Create the GraphicsPath for the shape (in this case
        '  an ellipse that fits inside the full control area)
        '  and apply it to the control by setting the Region
        '  property.
        path = New GraphicsPath
        path.AddEllipse(Me.ClientRectangle)
        Me.Region = New Region(path)

    End Sub
    Protected Overrides Sub OnPaint(ByVal e As System.Windows.Forms.PaintEventArgs)

        MyBase.OnPaint(e)

        If path IsNot Nothing Then
            e.Graphics.SmoothingMode = SmoothingMode.AntiAlias
            e.Graphics.FillPath(New SolidBrush(Me.BackColor), path)
            e.Graphics.DrawPath(New Pen(Me.ForeColor, 4), path)
        End If

    End Sub
    Private Sub EllipseShape_Resize(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Resize

        RefreshPath()
        Me.Invalidate()

    End Sub

End Class