Imports System
Imports System.Drawing
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe10-04.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe10_04

    '  Tracks when drag mode is on.
    Private isDraggingA As Boolean = False
    Private isDraggingB As Boolean = False

    '  The ellipse shape controls.
    Private ellipseA, ellipseB As EllipseShape
    Private Sub Recipe10_04_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        '  Create and configure both ellipses.
        ellipseA = New EllipseShape
        ellipseA.Width = 100
        ellipseA.Height = 100
        ellipseA.Top = 30
        ellipseA.Left = 30
        ellipseA.BackColor = Color.Red
        Me.Controls.Add(ellipseA)

        ellipseB = New EllipseShape
        ellipseB.Width = 100
        ellipseB.Height = 100
        ellipseB.Top = 130
        ellipseB.Left = 130
        ellipseB.BackColor = Color.LightSteelBlue
        Me.Controls.Add(ellipseB)

        '  Attach both ellipses to the same set of event handlers.
        AddHandler ellipseA.MouseDown, AddressOf Ellipse_MouseDown
        AddHandler ellipseA.MouseUp, AddressOf Ellipse_MouseUp
        AddHandler ellipseA.MouseMove, AddressOf Ellipse_MouseMove

        AddHandler ellipseB.MouseDown, AddressOf Ellipse_MouseDown
        AddHandler ellipseB.MouseUp, AddressOf Ellipse_MouseUp
        AddHandler ellipseB.MouseMove, AddressOf Ellipse_MouseMove

    End Sub
    Private Sub Ellipse_MouseDown(ByVal sender As Object, ByVal e As MouseEventArgs)

        If e.Button = Windows.Forms.MouseButtons.Left Then
            '  Get the ellipse that triggered this event.
            Dim ctrl As Control = DirectCast(sender, Control)
            ctrl.Tag = New Point(e.X, e.Y)

            If ctrl Is ellipseA Then
                isDraggingA = True
            Else
                isDraggingB = True
            End If
        End If

    End Sub
    Private Sub Ellipse_MouseUp(ByVal sender As Object, ByVal e As MouseEventArgs)

        isDraggingA = False
        isDraggingB = False

    End Sub
    Private Sub Ellipse_MouseMove(ByVal sender As Object, ByVal e As MouseEventArgs)

        '  Get the ellipse that triggered this event.
        Dim ctrl As Control = DirectCast(sender, Control)

        If (isDraggingA And (ctrl Is ellipseA)) Or (isDraggingB And (ctrl Is ellipseB)) Then

            '  Get the offset.
            Dim pnt As Point = DirectCast(ctrl.Tag, Point)

            '  Move the control.
            ctrl.Left = e.X + ctrl.Left - pnt.X
            ctrl.Top = e.Y + ctrl.Top - pnt.Y

        End If

    End Sub

End Class
