Imports System
Imports System.Drawing
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe10-08.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe10_08

    Private thumbNail As Image
    Private Sub Recipe10_08_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Using img As Image = Image.FromFile("test.jpg")

            Dim thumbnailWidth As Integer = 0
            Dim thumbnailHeight As Integer = 0

            '  Adjust the largest dimension to 200 pixels.
            '  This ensures that a thumbnail will not be larger than
            '  200x200 pixel square for each one.
            If img.Width > img.Height Then
                thumbnailWidth = 200
                thumbnailHeight = Convert.ToInt32((CSng(200) / img.Width) * img.Height)
            Else
                thumbnailHeight = 200
                thumbnailWidth = Convert.ToInt32((CSng(200) / img.Height) * img.Height)
            End If

            thumbNail = img.GetThumbnailImage(thumbnailWidth, thumbnailHeight, Nothing, IntPtr.Zero)

        End Using

    End Sub
    Private Sub Recipe10_08_Paint(ByVal sender As Object, ByVal e As System.Windows.Forms.PaintEventArgs) Handles Me.Paint
        e.Graphics.DrawImage(thumbNail, 10, 10)
    End Sub

End Class
