Imports System
Imports System.Windows.Forms
Imports System.Media
'  All designed code is stored in the autogenerated partial
'  class called Recipe10-09.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe10_09

    Private Sub Recipe10_09_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        '  Play a beep with default frequency and
        '  duration (800 and 200, respectively)
        Console.Beep()

        '  Play a beep with frequency as 200 and duration as 300.
        Console.Beep(200, 300)

        '  Play the sound associated with the Asterisk event.
        SystemSounds.Asterisk.Play()

    End Sub

End Class

