Imports System
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe09-14.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe09_14

    '  Boolean member tracks whether the form is in drag mode.
    '  If it is, mouse movements over the label will be translated
    '  intor form movements.
    Private dragging As Boolean
    '  Stores the offset where the label is clicked.
    Private pointClicked As Point
    '  MouseDown event handler for the label initiates the dragging process.
    Private Sub lblDrag_MouseDown(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles lblDrag.MouseDown

        If e.Button = Windows.Forms.MouseButtons.Left Then
            '  Turn the drag mode on and store the point clicked.
            dragging = True
            pointClicked = New Point(e.X, e.Y)
        Else
            dragging = False
        End If

    End Sub
    '  MouseMove event handler for the label processes dragging movements if
    '  the form is in drag mode.
    Private Sub lblDrag_MouseMove(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles lblDrag.MouseMove

        If dragging Then

            Dim pointMoveTo As Point

            '  Find the current mouse position in screen coordinates.
            pointMoveTo = Me.PointToScreen(New Point(e.X, e.Y))

            '  Compensate for the position of the control clicked.
            pointMoveTo.Offset(-pointClicked.X, -pointClicked.Y)

            '  Move the form.
            Me.Location = pointMoveTo

        End If

    End Sub
    '  MouseUp even handler for the label switches off drag mode.
    Private Sub lblDrag_MouseUp(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles lblDrag.MouseUp
        dragging = False
    End Sub
    Private Sub cmdClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdClose.Click
        Me.Close()
    End Sub

End Class
