Imports System
Imports System.Windows.Forms
Imports System.Runtime.InteropServices
Imports System.Text
'  All designed code is stored in the autogenerated partial
'  class called Recipe13-02.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe13_02

    '  Declare external functions.
    <DllImport("user32.dll")> _
    Private Shared Function GetForegroundWindow() As IntPtr
    End Function
    <DllImport("user32.dll")> _
    Private Shared Function GetWindowText(ByVal hWnd As IntPtr, ByVal text As StringBuilder, ByVal count As Integer) As Integer
    End Function
    Private Sub tmrRefresh_Tick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles tmrRefresh.Tick

        Dim chars As Integer = 256
        Dim buff As New StringBuilder(chars)

        '  Obtain the handle of the active window.
        Dim handle As IntPtr = GetForeGroundWindow()

        '  Update the controls.
        If GetWindowText(handle, buff, chars) > 0 Then
            lblCaption.Text = buff.ToString
            lblHandle.Text = handle.ToString

            If handle = Me.Handle Then

                lblCurrent.Text = "True"
            Else
                lblCurrent.Text = "False"
            End If

        End If

    End Sub

End Class
