'  All designed code is stored in the autogenerated partial
'  class called Recipe09-18.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe09_18

End Class
