Imports System
Imports System.Drawing
Imports System.Windows.Forms
Imports System.Drawing.Printing
Imports System.IO
'  All designed code is stored in the autogenerated partial
'  class called Recipe10-14.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe10_14

    Private Sub cmdPrint_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdPrint.Click

        '  Create the document and attach an event handler.
        Dim doc As New PrintDocument

        AddHandler doc.PrintPage, AddressOf Doc_PrintPage

        '  Allow the user to choose a printer and specify other settings.
        Dim dlgSettings As New PrintDialog
        dlgSettings.Document = doc

        '  If the user clicked OK, print the document.
        If dlgSettings.ShowDialog = Windows.Forms.DialogResult.OK Then
            '  This method returns immediately, before the print job starts.
            '  The PrintPage event will fire asynchronously.
            doc.Print()
        End If

    End Sub
    Private Sub Doc_PrintPage(ByVal sender As Object, ByVal e As PrintPageEventArgs)

        '  Determine the font.
        Using fnt As New Font("Arial", 30)
            '  Determine the postion on the page. In this case,
            '  we read the margin settings (although there is
            '  nothing that prevents your code from going outside
            '  the margin bounds).
            Dim x As Single = e.MarginBounds.Left
            Dim y As Single = e.MarginBounds.Top

            '  Determine the height of a line (based on the font used).
            Dim lineHeight As Single = Font.GetHeight(e.Graphics)

            '  Print five lines of text.
            For i As Integer = 1 To 5
                '  Draw the text with a black brush, using the
                '  font and coordinates we have determined.
                e.Graphics.DrawString("This is line " & i.ToString, Font, Brushes.Black, x, y)

                '  Move down the equivalent spacing of one line.
                y += lineheight
            Next
            y += lineHeight

            '  Draw an image.
            e.Graphics.DrawImage(Image.FromFile(Path.Combine(Application.StartupPath, "test.jpg")), x, y)

        End Using

    End Sub

End Class