Imports System
Imports System.Drawing
Imports System.Windows.Forms
Imports System.Drawing.Drawing2D
'  All designed code is stored in the autogenerated partial
'  class called Recipe10-03.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe10_03

    Private Sub Recipe10_03_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Dim path As New GraphicsPath
        Dim pointsA As Point() = New Point() {New Point(0, 0), New Point(40, 60), New Point(Me.Width - 100, 10)}
        Dim pointsB As Point() = New Point() {New Point(Me.Width - 40, Me.Height - 60), New Point(Me.Width, Me.Height), New Point(10, Me.Height)}

        path.AddCurve(pointsA)
        path.AddCurve(pointsB)

        path.CloseAllFigures()

        Me.Region = New Region(path)

    End Sub
    Private Sub cmdClose_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdClose.Click

        Me.Close()

    End Sub

End Class
