Imports System
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe09-08.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe09_08

    Private Sub btnTime_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnTime.Click

        '  Set the input mask to that of a short time.
        Me.mskTextBox.UseSystemPasswordChar = False
        Me.mskTextBox.Mask = "00:00"
        Me.lblActiveMask.Text = Me.mskTextBox.Mask
        Me.mskTextBox.Focus()

    End Sub
    Private Sub btnDecimal_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDecimal.Click

        '  Set the input mask to that of a decimal.
        Me.mskTextBox.UseSystemPasswordChar = False
        Me.mskTextBox.Mask = "999,999.00"
        Me.lblActiveMask.Text = Me.mskTextBox.Mask
        Me.mskTextBox.Focus()

    End Sub
    Private Sub btnDate_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDate.Click

        '  Set the input mask to that of a short date.
        Me.mskTextBox.UseSystemPasswordChar = False
        Me.mskTextBox.Mask = "00/00/0000"
        Me.lblActiveMask.Text = Me.mskTextBox.Mask
        Me.mskTextBox.Focus()

    End Sub
    Private Sub btnUSZip_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnUSZip.Click

        '  Set the input mask to that of a US ZIP code.
        Me.mskTextBox.UseSystemPasswordChar = False
        Me.mskTextBox.Mask = "00000-9999"
        Me.lblActiveMask.Text = Me.mskTextBox.Mask
        Me.mskTextBox.Focus()

    End Sub
    Private Sub btnUKPost_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnUKPost.Click

        '  Set the input mask to that of a OK postcode.
        Me.mskTextBox.UseSystemPasswordChar = False
        Me.mskTextBox.Mask = ">LCCC 9LL"
        Me.lblActiveMask.Text = Me.mskTextBox.Mask
        Me.mskTextBox.Focus()

    End Sub
    Private Sub btnSecret_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnPinNumber.Click

        '  Set the input mask to that of a secret pin.
        Me.mskTextBox.UseSystemPasswordChar = True
        Me.mskTextBox.Mask = "0000"
        Me.lblActiveMask.Text = Me.mskTextBox.Mask
        Me.mskTextBox.Focus()

    End Sub

End Class