Imports System
Imports System.IO
Imports Microsoft.VisualBasic
'  All designed code is stored in the autogenerated partial
'  class called DirectoryTree.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class DirectoryTree

    Private Sub DirectoryTree_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

        '  Set the first node.
        Dim rootNode As New TreeNode("C:\")
        treeDirectory.Nodes.Add(rootNode)

        '  Fill the first level and expand it.
        Fill(rootNode)
        treeDirectory.Nodes(0).Expand()

    End Sub
    Private Sub treeDirectory_BeforeExpand(ByVal sender As Object, ByVal e As System.Windows.Forms.TreeViewCancelEventArgs) Handles treeDirectory.BeforeExpand

        '  If a dummy node is found, remove it and read the
        '  real directory list.
        If e.Node.Nodes(0).Text = "*" Then
            e.Node.Nodes.Clear()
            Fill(e.Node)
        End If

    End Sub
    Private Sub Fill(ByVal dirNode As TreeNode)

        Dim dir As New DirectoryInfo(dirNode.FullPath)

        '  An exception could be thrown in this code if you don't
        '  have sufficient security permissions for a file or directory.
        '  You can catch and then ignore this exception.

        For Each dirItem As DirectoryInfo In dir.GetDirectories
            '  Add a node for the directory.
            Dim newNode As New TreeNode(dirItem.Name)
            dirNode.Nodes.Add(newNode)
            newNode.Nodes.Add("*")
        Next

    End Sub

End Class
