Imports System
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe09-05Parent.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe09_05Parent

    '  When the New menu item is clicked, create a new MDI child.
    Private Sub mnuNew_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles mnuNew.Click

        Dim frm As New Recipe09_05Child

        frm.MdiParent = Me
        frm.Show()

    End Sub

End Class