Imports System
Imports System.Windows.Controls
'  All designed code is stored in the autogenerated partial
'  class called Recipe13-11.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Public Class Recipe13_11

    Dim WithEvents wpfButton As System.Windows.Controls.Button
    Private Sub Recipe13_11_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

        '  Create a new button instance.
        wpfButton = New System.Windows.Controls.Button

        '  Set a few properties.
        wpfButton.Name = "WPF_Button"
        wpfButton.Content = "WPF BUTTON"

        '  Add the button to the ElementHost control.
        ElementHost1.Child = wpfButton

    End Sub
    Private Sub wpfButton_Click(ByVal sender As Object, ByVal e As System.Windows.RoutedEventArgs) Handles wpfButton.Click

        MessageBox.Show("You just clicked the WPF Button.", "WPF Button clicked", MessageBoxButtons.OK)

    End Sub

End Class
