Imports System
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe09-11.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Public Class Recipe09_11

End Class
