Imports System
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe09-15.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe09_15

    '  An array to hold the set of Icons used to create the
    '  animation effect.
    Private images As Icon() = New Icon(8) {}

    '  An integer to identify the current icon to display.
    Dim offset As Integer = 0
    Private Sub Recipe09_15_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        '  Load the basic set of eight icons.
        images(0) = New Icon("moon01.ico")
        images(1) = New Icon("moon02.ico")
        images(2) = New Icon("moon03.ico")
        images(3) = New Icon("moon04.ico")
        images(4) = New Icon("moon05.ico")
        images(5) = New Icon("moon06.ico")
        images(6) = New Icon("moon07.ico")
        images(7) = New Icon("moon08.ico")

    End Sub
    Private Sub timer_Elapsed(ByVal sender As Object, ByVal e As System.Timers.ElapsedEventArgs) Handles timer.Elapsed

        '  Change the icon.  This event handler fires once every
        '  second (500ms).
        notifyIcon.Icon = images(offset)
        offset += 1
        If offset > 7 Then offset = 0

    End Sub

End Class
